{-
   METRO2 API

   Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.

   OpenAPI Version: 3.0.2
   METRO2 API API version: v1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : METRO2.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module METRO2.Logging
  ( module METRO2.LoggingKatip
  ) where

import METRO2.LoggingKatip

#else

module METRO2.Logging
  ( module METRO2.LoggingMonadLogger
  ) where

import METRO2.LoggingMonadLogger

#endif
