{-
   METRO2 API

   Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.

   OpenAPI Version: 3.0.2
   METRO2 API API version: v1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : METRO2.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module METRO2.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import METRO2.Model
import METRO2.Core


-- * BaseSegment

-- | 'baseSegmentBlockDescriptorWord' Lens
baseSegmentBlockDescriptorWordL :: Lens_' BaseSegment (Maybe Int)
baseSegmentBlockDescriptorWordL f BaseSegment{..} = (\baseSegmentBlockDescriptorWord -> BaseSegment { baseSegmentBlockDescriptorWord, ..} ) <$> f baseSegmentBlockDescriptorWord
{-# INLINE baseSegmentBlockDescriptorWordL #-}

-- | 'baseSegmentRecordDescriptorWord' Lens
baseSegmentRecordDescriptorWordL :: Lens_' BaseSegment (Int)
baseSegmentRecordDescriptorWordL f BaseSegment{..} = (\baseSegmentRecordDescriptorWord -> BaseSegment { baseSegmentRecordDescriptorWord, ..} ) <$> f baseSegmentRecordDescriptorWord
{-# INLINE baseSegmentRecordDescriptorWordL #-}

-- | 'baseSegmentTimeStamp' Lens
baseSegmentTimeStampL :: Lens_' BaseSegment (Maybe DateTime)
baseSegmentTimeStampL f BaseSegment{..} = (\baseSegmentTimeStamp -> BaseSegment { baseSegmentTimeStamp, ..} ) <$> f baseSegmentTimeStamp
{-# INLINE baseSegmentTimeStampL #-}

-- | 'baseSegmentIdentificationNumber' Lens
baseSegmentIdentificationNumberL :: Lens_' BaseSegment (Text)
baseSegmentIdentificationNumberL f BaseSegment{..} = (\baseSegmentIdentificationNumber -> BaseSegment { baseSegmentIdentificationNumber, ..} ) <$> f baseSegmentIdentificationNumber
{-# INLINE baseSegmentIdentificationNumberL #-}

-- | 'baseSegmentCycleIdentifier' Lens
baseSegmentCycleIdentifierL :: Lens_' BaseSegment (Maybe Text)
baseSegmentCycleIdentifierL f BaseSegment{..} = (\baseSegmentCycleIdentifier -> BaseSegment { baseSegmentCycleIdentifier, ..} ) <$> f baseSegmentCycleIdentifier
{-# INLINE baseSegmentCycleIdentifierL #-}

-- | 'baseSegmentConsumerAccountNumber' Lens
baseSegmentConsumerAccountNumberL :: Lens_' BaseSegment (Text)
baseSegmentConsumerAccountNumberL f BaseSegment{..} = (\baseSegmentConsumerAccountNumber -> BaseSegment { baseSegmentConsumerAccountNumber, ..} ) <$> f baseSegmentConsumerAccountNumber
{-# INLINE baseSegmentConsumerAccountNumberL #-}

-- | 'baseSegmentPortfolioType' Lens
baseSegmentPortfolioTypeL :: Lens_' BaseSegment (Maybe E'PortfolioType)
baseSegmentPortfolioTypeL f BaseSegment{..} = (\baseSegmentPortfolioType -> BaseSegment { baseSegmentPortfolioType, ..} ) <$> f baseSegmentPortfolioType
{-# INLINE baseSegmentPortfolioTypeL #-}

-- | 'baseSegmentAccountType' Lens
baseSegmentAccountTypeL :: Lens_' BaseSegment (Text)
baseSegmentAccountTypeL f BaseSegment{..} = (\baseSegmentAccountType -> BaseSegment { baseSegmentAccountType, ..} ) <$> f baseSegmentAccountType
{-# INLINE baseSegmentAccountTypeL #-}

-- | 'baseSegmentDateOpened' Lens
baseSegmentDateOpenedL :: Lens_' BaseSegment (Maybe DateTime)
baseSegmentDateOpenedL f BaseSegment{..} = (\baseSegmentDateOpened -> BaseSegment { baseSegmentDateOpened, ..} ) <$> f baseSegmentDateOpened
{-# INLINE baseSegmentDateOpenedL #-}

-- | 'baseSegmentCreditLimit' Lens
baseSegmentCreditLimitL :: Lens_' BaseSegment (Maybe Int)
baseSegmentCreditLimitL f BaseSegment{..} = (\baseSegmentCreditLimit -> BaseSegment { baseSegmentCreditLimit, ..} ) <$> f baseSegmentCreditLimit
{-# INLINE baseSegmentCreditLimitL #-}

-- | 'baseSegmentHighestCredit' Lens
baseSegmentHighestCreditL :: Lens_' BaseSegment (Int)
baseSegmentHighestCreditL f BaseSegment{..} = (\baseSegmentHighestCredit -> BaseSegment { baseSegmentHighestCredit, ..} ) <$> f baseSegmentHighestCredit
{-# INLINE baseSegmentHighestCreditL #-}

-- | 'baseSegmentTermsDuration' Lens
baseSegmentTermsDurationL :: Lens_' BaseSegment (Text)
baseSegmentTermsDurationL f BaseSegment{..} = (\baseSegmentTermsDuration -> BaseSegment { baseSegmentTermsDuration, ..} ) <$> f baseSegmentTermsDuration
{-# INLINE baseSegmentTermsDurationL #-}

-- | 'baseSegmentTermsFrequency' Lens
baseSegmentTermsFrequencyL :: Lens_' BaseSegment (Maybe E'TermsFrequency)
baseSegmentTermsFrequencyL f BaseSegment{..} = (\baseSegmentTermsFrequency -> BaseSegment { baseSegmentTermsFrequency, ..} ) <$> f baseSegmentTermsFrequency
{-# INLINE baseSegmentTermsFrequencyL #-}

-- | 'baseSegmentScheduledMonthlyPaymentAmount' Lens
baseSegmentScheduledMonthlyPaymentAmountL :: Lens_' BaseSegment (Maybe Int)
baseSegmentScheduledMonthlyPaymentAmountL f BaseSegment{..} = (\baseSegmentScheduledMonthlyPaymentAmount -> BaseSegment { baseSegmentScheduledMonthlyPaymentAmount, ..} ) <$> f baseSegmentScheduledMonthlyPaymentAmount
{-# INLINE baseSegmentScheduledMonthlyPaymentAmountL #-}

-- | 'baseSegmentActualPaymentAmount' Lens
baseSegmentActualPaymentAmountL :: Lens_' BaseSegment (Maybe Int)
baseSegmentActualPaymentAmountL f BaseSegment{..} = (\baseSegmentActualPaymentAmount -> BaseSegment { baseSegmentActualPaymentAmount, ..} ) <$> f baseSegmentActualPaymentAmount
{-# INLINE baseSegmentActualPaymentAmountL #-}

-- | 'baseSegmentAccountStatus' Lens
baseSegmentAccountStatusL :: Lens_' BaseSegment (E'AccountStatus)
baseSegmentAccountStatusL f BaseSegment{..} = (\baseSegmentAccountStatus -> BaseSegment { baseSegmentAccountStatus, ..} ) <$> f baseSegmentAccountStatus
{-# INLINE baseSegmentAccountStatusL #-}

-- | 'baseSegmentPaymentRating' Lens
baseSegmentPaymentRatingL :: Lens_' BaseSegment (Maybe E'PaymentRating)
baseSegmentPaymentRatingL f BaseSegment{..} = (\baseSegmentPaymentRating -> BaseSegment { baseSegmentPaymentRating, ..} ) <$> f baseSegmentPaymentRating
{-# INLINE baseSegmentPaymentRatingL #-}

-- | 'baseSegmentPaymentHistoryProfile' Lens
baseSegmentPaymentHistoryProfileL :: Lens_' BaseSegment (E'PaymentHistoryProfile)
baseSegmentPaymentHistoryProfileL f BaseSegment{..} = (\baseSegmentPaymentHistoryProfile -> BaseSegment { baseSegmentPaymentHistoryProfile, ..} ) <$> f baseSegmentPaymentHistoryProfile
{-# INLINE baseSegmentPaymentHistoryProfileL #-}

-- | 'baseSegmentSpecialComment' Lens
baseSegmentSpecialCommentL :: Lens_' BaseSegment (Maybe Text)
baseSegmentSpecialCommentL f BaseSegment{..} = (\baseSegmentSpecialComment -> BaseSegment { baseSegmentSpecialComment, ..} ) <$> f baseSegmentSpecialComment
{-# INLINE baseSegmentSpecialCommentL #-}

-- | 'baseSegmentComplianceConditionCode' Lens
baseSegmentComplianceConditionCodeL :: Lens_' BaseSegment (Maybe Text)
baseSegmentComplianceConditionCodeL f BaseSegment{..} = (\baseSegmentComplianceConditionCode -> BaseSegment { baseSegmentComplianceConditionCode, ..} ) <$> f baseSegmentComplianceConditionCode
{-# INLINE baseSegmentComplianceConditionCodeL #-}

-- | 'baseSegmentCurrentBalance' Lens
baseSegmentCurrentBalanceL :: Lens_' BaseSegment (Int)
baseSegmentCurrentBalanceL f BaseSegment{..} = (\baseSegmentCurrentBalance -> BaseSegment { baseSegmentCurrentBalance, ..} ) <$> f baseSegmentCurrentBalance
{-# INLINE baseSegmentCurrentBalanceL #-}

-- | 'baseSegmentAmountPastDue' Lens
baseSegmentAmountPastDueL :: Lens_' BaseSegment (Maybe Int)
baseSegmentAmountPastDueL f BaseSegment{..} = (\baseSegmentAmountPastDue -> BaseSegment { baseSegmentAmountPastDue, ..} ) <$> f baseSegmentAmountPastDue
{-# INLINE baseSegmentAmountPastDueL #-}

-- | 'baseSegmentOriginalChargeOffAmount' Lens
baseSegmentOriginalChargeOffAmountL :: Lens_' BaseSegment (Maybe Int)
baseSegmentOriginalChargeOffAmountL f BaseSegment{..} = (\baseSegmentOriginalChargeOffAmount -> BaseSegment { baseSegmentOriginalChargeOffAmount, ..} ) <$> f baseSegmentOriginalChargeOffAmount
{-# INLINE baseSegmentOriginalChargeOffAmountL #-}

-- | 'baseSegmentDateAccountInformation' Lens
baseSegmentDateAccountInformationL :: Lens_' BaseSegment (DateTime)
baseSegmentDateAccountInformationL f BaseSegment{..} = (\baseSegmentDateAccountInformation -> BaseSegment { baseSegmentDateAccountInformation, ..} ) <$> f baseSegmentDateAccountInformation
{-# INLINE baseSegmentDateAccountInformationL #-}

-- | 'baseSegmentDateFirstDelinquency' Lens
baseSegmentDateFirstDelinquencyL :: Lens_' BaseSegment (Maybe DateTime)
baseSegmentDateFirstDelinquencyL f BaseSegment{..} = (\baseSegmentDateFirstDelinquency -> BaseSegment { baseSegmentDateFirstDelinquency, ..} ) <$> f baseSegmentDateFirstDelinquency
{-# INLINE baseSegmentDateFirstDelinquencyL #-}

-- | 'baseSegmentDateClosed' Lens
baseSegmentDateClosedL :: Lens_' BaseSegment (Maybe DateTime)
baseSegmentDateClosedL f BaseSegment{..} = (\baseSegmentDateClosed -> BaseSegment { baseSegmentDateClosed, ..} ) <$> f baseSegmentDateClosed
{-# INLINE baseSegmentDateClosedL #-}

-- | 'baseSegmentDateLastPayment' Lens
baseSegmentDateLastPaymentL :: Lens_' BaseSegment (Maybe DateTime)
baseSegmentDateLastPaymentL f BaseSegment{..} = (\baseSegmentDateLastPayment -> BaseSegment { baseSegmentDateLastPayment, ..} ) <$> f baseSegmentDateLastPayment
{-# INLINE baseSegmentDateLastPaymentL #-}

-- | 'baseSegmentInterestTypeIndicator' Lens
baseSegmentInterestTypeIndicatorL :: Lens_' BaseSegment (Maybe Text)
baseSegmentInterestTypeIndicatorL f BaseSegment{..} = (\baseSegmentInterestTypeIndicator -> BaseSegment { baseSegmentInterestTypeIndicator, ..} ) <$> f baseSegmentInterestTypeIndicator
{-# INLINE baseSegmentInterestTypeIndicatorL #-}

-- | 'baseSegmentSurname' Lens
baseSegmentSurnameL :: Lens_' BaseSegment (Text)
baseSegmentSurnameL f BaseSegment{..} = (\baseSegmentSurname -> BaseSegment { baseSegmentSurname, ..} ) <$> f baseSegmentSurname
{-# INLINE baseSegmentSurnameL #-}

-- | 'baseSegmentFirstName' Lens
baseSegmentFirstNameL :: Lens_' BaseSegment (Text)
baseSegmentFirstNameL f BaseSegment{..} = (\baseSegmentFirstName -> BaseSegment { baseSegmentFirstName, ..} ) <$> f baseSegmentFirstName
{-# INLINE baseSegmentFirstNameL #-}

-- | 'baseSegmentMiddleName' Lens
baseSegmentMiddleNameL :: Lens_' BaseSegment (Maybe Text)
baseSegmentMiddleNameL f BaseSegment{..} = (\baseSegmentMiddleName -> BaseSegment { baseSegmentMiddleName, ..} ) <$> f baseSegmentMiddleName
{-# INLINE baseSegmentMiddleNameL #-}

-- | 'baseSegmentGenerationCode' Lens
baseSegmentGenerationCodeL :: Lens_' BaseSegment (Maybe E'GenerationCode)
baseSegmentGenerationCodeL f BaseSegment{..} = (\baseSegmentGenerationCode -> BaseSegment { baseSegmentGenerationCode, ..} ) <$> f baseSegmentGenerationCode
{-# INLINE baseSegmentGenerationCodeL #-}

-- | 'baseSegmentSocialSecurityNumber' Lens
baseSegmentSocialSecurityNumberL :: Lens_' BaseSegment (Int)
baseSegmentSocialSecurityNumberL f BaseSegment{..} = (\baseSegmentSocialSecurityNumber -> BaseSegment { baseSegmentSocialSecurityNumber, ..} ) <$> f baseSegmentSocialSecurityNumber
{-# INLINE baseSegmentSocialSecurityNumberL #-}

-- | 'baseSegmentDateBirth' Lens
baseSegmentDateBirthL :: Lens_' BaseSegment (DateTime)
baseSegmentDateBirthL f BaseSegment{..} = (\baseSegmentDateBirth -> BaseSegment { baseSegmentDateBirth, ..} ) <$> f baseSegmentDateBirth
{-# INLINE baseSegmentDateBirthL #-}

-- | 'baseSegmentTelephoneNumber' Lens
baseSegmentTelephoneNumberL :: Lens_' BaseSegment (Maybe Integer)
baseSegmentTelephoneNumberL f BaseSegment{..} = (\baseSegmentTelephoneNumber -> BaseSegment { baseSegmentTelephoneNumber, ..} ) <$> f baseSegmentTelephoneNumber
{-# INLINE baseSegmentTelephoneNumberL #-}

-- | 'baseSegmentEcoaCode' Lens
baseSegmentEcoaCodeL :: Lens_' BaseSegment (Text)
baseSegmentEcoaCodeL f BaseSegment{..} = (\baseSegmentEcoaCode -> BaseSegment { baseSegmentEcoaCode, ..} ) <$> f baseSegmentEcoaCode
{-# INLINE baseSegmentEcoaCodeL #-}

-- | 'baseSegmentConsumerInformationIndicator' Lens
baseSegmentConsumerInformationIndicatorL :: Lens_' BaseSegment (Maybe Text)
baseSegmentConsumerInformationIndicatorL f BaseSegment{..} = (\baseSegmentConsumerInformationIndicator -> BaseSegment { baseSegmentConsumerInformationIndicator, ..} ) <$> f baseSegmentConsumerInformationIndicator
{-# INLINE baseSegmentConsumerInformationIndicatorL #-}

-- | 'baseSegmentCountryCode' Lens
baseSegmentCountryCodeL :: Lens_' BaseSegment (Maybe Text)
baseSegmentCountryCodeL f BaseSegment{..} = (\baseSegmentCountryCode -> BaseSegment { baseSegmentCountryCode, ..} ) <$> f baseSegmentCountryCode
{-# INLINE baseSegmentCountryCodeL #-}

-- | 'baseSegmentFirstLineAddress' Lens
baseSegmentFirstLineAddressL :: Lens_' BaseSegment (Text)
baseSegmentFirstLineAddressL f BaseSegment{..} = (\baseSegmentFirstLineAddress -> BaseSegment { baseSegmentFirstLineAddress, ..} ) <$> f baseSegmentFirstLineAddress
{-# INLINE baseSegmentFirstLineAddressL #-}

-- | 'baseSegmentSecondLineAddress' Lens
baseSegmentSecondLineAddressL :: Lens_' BaseSegment (Maybe Text)
baseSegmentSecondLineAddressL f BaseSegment{..} = (\baseSegmentSecondLineAddress -> BaseSegment { baseSegmentSecondLineAddress, ..} ) <$> f baseSegmentSecondLineAddress
{-# INLINE baseSegmentSecondLineAddressL #-}

-- | 'baseSegmentCity' Lens
baseSegmentCityL :: Lens_' BaseSegment (Maybe Text)
baseSegmentCityL f BaseSegment{..} = (\baseSegmentCity -> BaseSegment { baseSegmentCity, ..} ) <$> f baseSegmentCity
{-# INLINE baseSegmentCityL #-}

-- | 'baseSegmentState' Lens
baseSegmentStateL :: Lens_' BaseSegment (Text)
baseSegmentStateL f BaseSegment{..} = (\baseSegmentState -> BaseSegment { baseSegmentState, ..} ) <$> f baseSegmentState
{-# INLINE baseSegmentStateL #-}

-- | 'baseSegmentZipCode' Lens
baseSegmentZipCodeL :: Lens_' BaseSegment (Text)
baseSegmentZipCodeL f BaseSegment{..} = (\baseSegmentZipCode -> BaseSegment { baseSegmentZipCode, ..} ) <$> f baseSegmentZipCode
{-# INLINE baseSegmentZipCodeL #-}

-- | 'baseSegmentAddressIndicator' Lens
baseSegmentAddressIndicatorL :: Lens_' BaseSegment (Maybe E'AddressIndicator)
baseSegmentAddressIndicatorL f BaseSegment{..} = (\baseSegmentAddressIndicator -> BaseSegment { baseSegmentAddressIndicator, ..} ) <$> f baseSegmentAddressIndicator
{-# INLINE baseSegmentAddressIndicatorL #-}

-- | 'baseSegmentResidenceCode' Lens
baseSegmentResidenceCodeL :: Lens_' BaseSegment (Maybe E'ResidenceCode)
baseSegmentResidenceCodeL f BaseSegment{..} = (\baseSegmentResidenceCode -> BaseSegment { baseSegmentResidenceCode, ..} ) <$> f baseSegmentResidenceCode
{-# INLINE baseSegmentResidenceCodeL #-}



-- * DataRecord

-- | 'dataRecordBase' Lens
dataRecordBaseL :: Lens_' DataRecord (BaseSegment)
dataRecordBaseL f DataRecord{..} = (\dataRecordBase -> DataRecord { dataRecordBase, ..} ) <$> f dataRecordBase
{-# INLINE dataRecordBaseL #-}

-- | 'dataRecordJ1' Lens
dataRecordJ1L :: Lens_' DataRecord (Maybe [J1Segment])
dataRecordJ1L f DataRecord{..} = (\dataRecordJ1 -> DataRecord { dataRecordJ1, ..} ) <$> f dataRecordJ1
{-# INLINE dataRecordJ1L #-}

-- | 'dataRecordJ2' Lens
dataRecordJ2L :: Lens_' DataRecord (Maybe [J2Segment])
dataRecordJ2L f DataRecord{..} = (\dataRecordJ2 -> DataRecord { dataRecordJ2, ..} ) <$> f dataRecordJ2
{-# INLINE dataRecordJ2L #-}

-- | 'dataRecordK1' Lens
dataRecordK1L :: Lens_' DataRecord (Maybe K1Segment)
dataRecordK1L f DataRecord{..} = (\dataRecordK1 -> DataRecord { dataRecordK1, ..} ) <$> f dataRecordK1
{-# INLINE dataRecordK1L #-}

-- | 'dataRecordK2' Lens
dataRecordK2L :: Lens_' DataRecord (Maybe K2Segment)
dataRecordK2L f DataRecord{..} = (\dataRecordK2 -> DataRecord { dataRecordK2, ..} ) <$> f dataRecordK2
{-# INLINE dataRecordK2L #-}

-- | 'dataRecordK3' Lens
dataRecordK3L :: Lens_' DataRecord (Maybe K3Segment)
dataRecordK3L f DataRecord{..} = (\dataRecordK3 -> DataRecord { dataRecordK3, ..} ) <$> f dataRecordK3
{-# INLINE dataRecordK3L #-}

-- | 'dataRecordK4' Lens
dataRecordK4L :: Lens_' DataRecord (Maybe K4Segment)
dataRecordK4L f DataRecord{..} = (\dataRecordK4 -> DataRecord { dataRecordK4, ..} ) <$> f dataRecordK4
{-# INLINE dataRecordK4L #-}

-- | 'dataRecordL1' Lens
dataRecordL1L :: Lens_' DataRecord (Maybe L1Segment)
dataRecordL1L f DataRecord{..} = (\dataRecordL1 -> DataRecord { dataRecordL1, ..} ) <$> f dataRecordL1
{-# INLINE dataRecordL1L #-}

-- | 'dataRecordN1' Lens
dataRecordN1L :: Lens_' DataRecord (Maybe N1Segment)
dataRecordN1L f DataRecord{..} = (\dataRecordN1 -> DataRecord { dataRecordN1, ..} ) <$> f dataRecordN1
{-# INLINE dataRecordN1L #-}



-- * File

-- | 'fileHeader' Lens
fileHeaderL :: Lens_' File (HeaderRecord)
fileHeaderL f File{..} = (\fileHeader -> File { fileHeader, ..} ) <$> f fileHeader
{-# INLINE fileHeaderL #-}

-- | 'fileData' Lens
fileDataL :: Lens_' File (Maybe [DataRecord])
fileDataL f File{..} = (\fileData -> File { fileData, ..} ) <$> f fileData
{-# INLINE fileDataL #-}

-- | 'fileTrailer' Lens
fileTrailerL :: Lens_' File (TrailerRecord)
fileTrailerL f File{..} = (\fileTrailer -> File { fileTrailer, ..} ) <$> f fileTrailer
{-# INLINE fileTrailerL #-}



-- * HeaderRecord

-- | 'headerRecordBlockDescriptorWord' Lens
headerRecordBlockDescriptorWordL :: Lens_' HeaderRecord (Maybe Int)
headerRecordBlockDescriptorWordL f HeaderRecord{..} = (\headerRecordBlockDescriptorWord -> HeaderRecord { headerRecordBlockDescriptorWord, ..} ) <$> f headerRecordBlockDescriptorWord
{-# INLINE headerRecordBlockDescriptorWordL #-}

-- | 'headerRecordRecordDescriptorWord' Lens
headerRecordRecordDescriptorWordL :: Lens_' HeaderRecord (Int)
headerRecordRecordDescriptorWordL f HeaderRecord{..} = (\headerRecordRecordDescriptorWord -> HeaderRecord { headerRecordRecordDescriptorWord, ..} ) <$> f headerRecordRecordDescriptorWord
{-# INLINE headerRecordRecordDescriptorWordL #-}

-- | 'headerRecordRecordIdentifier' Lens
headerRecordRecordIdentifierL :: Lens_' HeaderRecord (E'RecordIdentifier)
headerRecordRecordIdentifierL f HeaderRecord{..} = (\headerRecordRecordIdentifier -> HeaderRecord { headerRecordRecordIdentifier, ..} ) <$> f headerRecordRecordIdentifier
{-# INLINE headerRecordRecordIdentifierL #-}

-- | 'headerRecordCycleIdentifier' Lens
headerRecordCycleIdentifierL :: Lens_' HeaderRecord (Maybe Text)
headerRecordCycleIdentifierL f HeaderRecord{..} = (\headerRecordCycleIdentifier -> HeaderRecord { headerRecordCycleIdentifier, ..} ) <$> f headerRecordCycleIdentifier
{-# INLINE headerRecordCycleIdentifierL #-}

-- | 'headerRecordInnovisProgramIdentifier' Lens
headerRecordInnovisProgramIdentifierL :: Lens_' HeaderRecord (Maybe Text)
headerRecordInnovisProgramIdentifierL f HeaderRecord{..} = (\headerRecordInnovisProgramIdentifier -> HeaderRecord { headerRecordInnovisProgramIdentifier, ..} ) <$> f headerRecordInnovisProgramIdentifier
{-# INLINE headerRecordInnovisProgramIdentifierL #-}

-- | 'headerRecordEquifaxProgramIdentifier' Lens
headerRecordEquifaxProgramIdentifierL :: Lens_' HeaderRecord (Maybe Text)
headerRecordEquifaxProgramIdentifierL f HeaderRecord{..} = (\headerRecordEquifaxProgramIdentifier -> HeaderRecord { headerRecordEquifaxProgramIdentifier, ..} ) <$> f headerRecordEquifaxProgramIdentifier
{-# INLINE headerRecordEquifaxProgramIdentifierL #-}

-- | 'headerRecordExperianProgramIdentifier' Lens
headerRecordExperianProgramIdentifierL :: Lens_' HeaderRecord (Maybe Text)
headerRecordExperianProgramIdentifierL f HeaderRecord{..} = (\headerRecordExperianProgramIdentifier -> HeaderRecord { headerRecordExperianProgramIdentifier, ..} ) <$> f headerRecordExperianProgramIdentifier
{-# INLINE headerRecordExperianProgramIdentifierL #-}

-- | 'headerRecordTransUnionProgramIdentifier' Lens
headerRecordTransUnionProgramIdentifierL :: Lens_' HeaderRecord (Maybe Text)
headerRecordTransUnionProgramIdentifierL f HeaderRecord{..} = (\headerRecordTransUnionProgramIdentifier -> HeaderRecord { headerRecordTransUnionProgramIdentifier, ..} ) <$> f headerRecordTransUnionProgramIdentifier
{-# INLINE headerRecordTransUnionProgramIdentifierL #-}

-- | 'headerRecordActivityDate' Lens
headerRecordActivityDateL :: Lens_' HeaderRecord (DateTime)
headerRecordActivityDateL f HeaderRecord{..} = (\headerRecordActivityDate -> HeaderRecord { headerRecordActivityDate, ..} ) <$> f headerRecordActivityDate
{-# INLINE headerRecordActivityDateL #-}

-- | 'headerRecordDateCreated' Lens
headerRecordDateCreatedL :: Lens_' HeaderRecord (DateTime)
headerRecordDateCreatedL f HeaderRecord{..} = (\headerRecordDateCreated -> HeaderRecord { headerRecordDateCreated, ..} ) <$> f headerRecordDateCreated
{-# INLINE headerRecordDateCreatedL #-}

-- | 'headerRecordProgramDate' Lens
headerRecordProgramDateL :: Lens_' HeaderRecord (Maybe DateTime)
headerRecordProgramDateL f HeaderRecord{..} = (\headerRecordProgramDate -> HeaderRecord { headerRecordProgramDate, ..} ) <$> f headerRecordProgramDate
{-# INLINE headerRecordProgramDateL #-}

-- | 'headerRecordProgramRevisionDate' Lens
headerRecordProgramRevisionDateL :: Lens_' HeaderRecord (Maybe DateTime)
headerRecordProgramRevisionDateL f HeaderRecord{..} = (\headerRecordProgramRevisionDate -> HeaderRecord { headerRecordProgramRevisionDate, ..} ) <$> f headerRecordProgramRevisionDate
{-# INLINE headerRecordProgramRevisionDateL #-}

-- | 'headerRecordReporterName' Lens
headerRecordReporterNameL :: Lens_' HeaderRecord (Text)
headerRecordReporterNameL f HeaderRecord{..} = (\headerRecordReporterName -> HeaderRecord { headerRecordReporterName, ..} ) <$> f headerRecordReporterName
{-# INLINE headerRecordReporterNameL #-}

-- | 'headerRecordReporterAddress' Lens
headerRecordReporterAddressL :: Lens_' HeaderRecord (Text)
headerRecordReporterAddressL f HeaderRecord{..} = (\headerRecordReporterAddress -> HeaderRecord { headerRecordReporterAddress, ..} ) <$> f headerRecordReporterAddress
{-# INLINE headerRecordReporterAddressL #-}

-- | 'headerRecordReporterTelephoneNumber' Lens
headerRecordReporterTelephoneNumberL :: Lens_' HeaderRecord (Maybe Integer)
headerRecordReporterTelephoneNumberL f HeaderRecord{..} = (\headerRecordReporterTelephoneNumber -> HeaderRecord { headerRecordReporterTelephoneNumber, ..} ) <$> f headerRecordReporterTelephoneNumber
{-# INLINE headerRecordReporterTelephoneNumberL #-}

-- | 'headerRecordSoftwareVendorName' Lens
headerRecordSoftwareVendorNameL :: Lens_' HeaderRecord (Maybe Text)
headerRecordSoftwareVendorNameL f HeaderRecord{..} = (\headerRecordSoftwareVendorName -> HeaderRecord { headerRecordSoftwareVendorName, ..} ) <$> f headerRecordSoftwareVendorName
{-# INLINE headerRecordSoftwareVendorNameL #-}

-- | 'headerRecordSoftwareVersionNumber' Lens
headerRecordSoftwareVersionNumberL :: Lens_' HeaderRecord (Maybe Text)
headerRecordSoftwareVersionNumberL f HeaderRecord{..} = (\headerRecordSoftwareVersionNumber -> HeaderRecord { headerRecordSoftwareVersionNumber, ..} ) <$> f headerRecordSoftwareVersionNumber
{-# INLINE headerRecordSoftwareVersionNumberL #-}

-- | 'headerRecordPrbcProgramIdentifier' Lens
headerRecordPrbcProgramIdentifierL :: Lens_' HeaderRecord (Maybe Text)
headerRecordPrbcProgramIdentifierL f HeaderRecord{..} = (\headerRecordPrbcProgramIdentifier -> HeaderRecord { headerRecordPrbcProgramIdentifier, ..} ) <$> f headerRecordPrbcProgramIdentifier
{-# INLINE headerRecordPrbcProgramIdentifierL #-}



-- * J1Segment

-- | 'j1SegmentSegmentIdentifier' Lens
j1SegmentSegmentIdentifierL :: Lens_' J1Segment (E'SegmentIdentifier)
j1SegmentSegmentIdentifierL f J1Segment{..} = (\j1SegmentSegmentIdentifier -> J1Segment { j1SegmentSegmentIdentifier, ..} ) <$> f j1SegmentSegmentIdentifier
{-# INLINE j1SegmentSegmentIdentifierL #-}

-- | 'j1SegmentSurname' Lens
j1SegmentSurnameL :: Lens_' J1Segment (Text)
j1SegmentSurnameL f J1Segment{..} = (\j1SegmentSurname -> J1Segment { j1SegmentSurname, ..} ) <$> f j1SegmentSurname
{-# INLINE j1SegmentSurnameL #-}

-- | 'j1SegmentFirstName' Lens
j1SegmentFirstNameL :: Lens_' J1Segment (Text)
j1SegmentFirstNameL f J1Segment{..} = (\j1SegmentFirstName -> J1Segment { j1SegmentFirstName, ..} ) <$> f j1SegmentFirstName
{-# INLINE j1SegmentFirstNameL #-}

-- | 'j1SegmentMiddleName' Lens
j1SegmentMiddleNameL :: Lens_' J1Segment (Maybe Text)
j1SegmentMiddleNameL f J1Segment{..} = (\j1SegmentMiddleName -> J1Segment { j1SegmentMiddleName, ..} ) <$> f j1SegmentMiddleName
{-# INLINE j1SegmentMiddleNameL #-}

-- | 'j1SegmentGenerationCode' Lens
j1SegmentGenerationCodeL :: Lens_' J1Segment (Maybe E'GenerationCode2)
j1SegmentGenerationCodeL f J1Segment{..} = (\j1SegmentGenerationCode -> J1Segment { j1SegmentGenerationCode, ..} ) <$> f j1SegmentGenerationCode
{-# INLINE j1SegmentGenerationCodeL #-}

-- | 'j1SegmentSocialSecurityNumber' Lens
j1SegmentSocialSecurityNumberL :: Lens_' J1Segment (Int)
j1SegmentSocialSecurityNumberL f J1Segment{..} = (\j1SegmentSocialSecurityNumber -> J1Segment { j1SegmentSocialSecurityNumber, ..} ) <$> f j1SegmentSocialSecurityNumber
{-# INLINE j1SegmentSocialSecurityNumberL #-}

-- | 'j1SegmentDateBirth' Lens
j1SegmentDateBirthL :: Lens_' J1Segment (DateTime)
j1SegmentDateBirthL f J1Segment{..} = (\j1SegmentDateBirth -> J1Segment { j1SegmentDateBirth, ..} ) <$> f j1SegmentDateBirth
{-# INLINE j1SegmentDateBirthL #-}

-- | 'j1SegmentTelephoneNumber' Lens
j1SegmentTelephoneNumberL :: Lens_' J1Segment (Maybe Integer)
j1SegmentTelephoneNumberL f J1Segment{..} = (\j1SegmentTelephoneNumber -> J1Segment { j1SegmentTelephoneNumber, ..} ) <$> f j1SegmentTelephoneNumber
{-# INLINE j1SegmentTelephoneNumberL #-}

-- | 'j1SegmentEcoaCode' Lens
j1SegmentEcoaCodeL :: Lens_' J1Segment (Text)
j1SegmentEcoaCodeL f J1Segment{..} = (\j1SegmentEcoaCode -> J1Segment { j1SegmentEcoaCode, ..} ) <$> f j1SegmentEcoaCode
{-# INLINE j1SegmentEcoaCodeL #-}

-- | 'j1SegmentConsumerInformationIndicator' Lens
j1SegmentConsumerInformationIndicatorL :: Lens_' J1Segment (Maybe Text)
j1SegmentConsumerInformationIndicatorL f J1Segment{..} = (\j1SegmentConsumerInformationIndicator -> J1Segment { j1SegmentConsumerInformationIndicator, ..} ) <$> f j1SegmentConsumerInformationIndicator
{-# INLINE j1SegmentConsumerInformationIndicatorL #-}



-- * J2Segment

-- | 'j2SegmentSegmentIdentifier' Lens
j2SegmentSegmentIdentifierL :: Lens_' J2Segment (E'SegmentIdentifier2)
j2SegmentSegmentIdentifierL f J2Segment{..} = (\j2SegmentSegmentIdentifier -> J2Segment { j2SegmentSegmentIdentifier, ..} ) <$> f j2SegmentSegmentIdentifier
{-# INLINE j2SegmentSegmentIdentifierL #-}

-- | 'j2SegmentSurname' Lens
j2SegmentSurnameL :: Lens_' J2Segment (Text)
j2SegmentSurnameL f J2Segment{..} = (\j2SegmentSurname -> J2Segment { j2SegmentSurname, ..} ) <$> f j2SegmentSurname
{-# INLINE j2SegmentSurnameL #-}

-- | 'j2SegmentFirstName' Lens
j2SegmentFirstNameL :: Lens_' J2Segment (Text)
j2SegmentFirstNameL f J2Segment{..} = (\j2SegmentFirstName -> J2Segment { j2SegmentFirstName, ..} ) <$> f j2SegmentFirstName
{-# INLINE j2SegmentFirstNameL #-}

-- | 'j2SegmentMiddleName' Lens
j2SegmentMiddleNameL :: Lens_' J2Segment (Maybe Text)
j2SegmentMiddleNameL f J2Segment{..} = (\j2SegmentMiddleName -> J2Segment { j2SegmentMiddleName, ..} ) <$> f j2SegmentMiddleName
{-# INLINE j2SegmentMiddleNameL #-}

-- | 'j2SegmentGenerationCode' Lens
j2SegmentGenerationCodeL :: Lens_' J2Segment (Maybe E'GenerationCode2)
j2SegmentGenerationCodeL f J2Segment{..} = (\j2SegmentGenerationCode -> J2Segment { j2SegmentGenerationCode, ..} ) <$> f j2SegmentGenerationCode
{-# INLINE j2SegmentGenerationCodeL #-}

-- | 'j2SegmentSocialSecurityNumber' Lens
j2SegmentSocialSecurityNumberL :: Lens_' J2Segment (Int)
j2SegmentSocialSecurityNumberL f J2Segment{..} = (\j2SegmentSocialSecurityNumber -> J2Segment { j2SegmentSocialSecurityNumber, ..} ) <$> f j2SegmentSocialSecurityNumber
{-# INLINE j2SegmentSocialSecurityNumberL #-}

-- | 'j2SegmentDateBirth' Lens
j2SegmentDateBirthL :: Lens_' J2Segment (DateTime)
j2SegmentDateBirthL f J2Segment{..} = (\j2SegmentDateBirth -> J2Segment { j2SegmentDateBirth, ..} ) <$> f j2SegmentDateBirth
{-# INLINE j2SegmentDateBirthL #-}

-- | 'j2SegmentTelephoneNumber' Lens
j2SegmentTelephoneNumberL :: Lens_' J2Segment (Maybe Integer)
j2SegmentTelephoneNumberL f J2Segment{..} = (\j2SegmentTelephoneNumber -> J2Segment { j2SegmentTelephoneNumber, ..} ) <$> f j2SegmentTelephoneNumber
{-# INLINE j2SegmentTelephoneNumberL #-}

-- | 'j2SegmentEcoaCode' Lens
j2SegmentEcoaCodeL :: Lens_' J2Segment (Text)
j2SegmentEcoaCodeL f J2Segment{..} = (\j2SegmentEcoaCode -> J2Segment { j2SegmentEcoaCode, ..} ) <$> f j2SegmentEcoaCode
{-# INLINE j2SegmentEcoaCodeL #-}

-- | 'j2SegmentConsumerInformationIndicator' Lens
j2SegmentConsumerInformationIndicatorL :: Lens_' J2Segment (Maybe Text)
j2SegmentConsumerInformationIndicatorL f J2Segment{..} = (\j2SegmentConsumerInformationIndicator -> J2Segment { j2SegmentConsumerInformationIndicator, ..} ) <$> f j2SegmentConsumerInformationIndicator
{-# INLINE j2SegmentConsumerInformationIndicatorL #-}

-- | 'j2SegmentCountryCode' Lens
j2SegmentCountryCodeL :: Lens_' J2Segment (Maybe Text)
j2SegmentCountryCodeL f J2Segment{..} = (\j2SegmentCountryCode -> J2Segment { j2SegmentCountryCode, ..} ) <$> f j2SegmentCountryCode
{-# INLINE j2SegmentCountryCodeL #-}

-- | 'j2SegmentFirstLineAddress' Lens
j2SegmentFirstLineAddressL :: Lens_' J2Segment (Text)
j2SegmentFirstLineAddressL f J2Segment{..} = (\j2SegmentFirstLineAddress -> J2Segment { j2SegmentFirstLineAddress, ..} ) <$> f j2SegmentFirstLineAddress
{-# INLINE j2SegmentFirstLineAddressL #-}

-- | 'j2SegmentSecondLineAddress' Lens
j2SegmentSecondLineAddressL :: Lens_' J2Segment (Maybe Text)
j2SegmentSecondLineAddressL f J2Segment{..} = (\j2SegmentSecondLineAddress -> J2Segment { j2SegmentSecondLineAddress, ..} ) <$> f j2SegmentSecondLineAddress
{-# INLINE j2SegmentSecondLineAddressL #-}

-- | 'j2SegmentCity' Lens
j2SegmentCityL :: Lens_' J2Segment (Text)
j2SegmentCityL f J2Segment{..} = (\j2SegmentCity -> J2Segment { j2SegmentCity, ..} ) <$> f j2SegmentCity
{-# INLINE j2SegmentCityL #-}

-- | 'j2SegmentState' Lens
j2SegmentStateL :: Lens_' J2Segment (Text)
j2SegmentStateL f J2Segment{..} = (\j2SegmentState -> J2Segment { j2SegmentState, ..} ) <$> f j2SegmentState
{-# INLINE j2SegmentStateL #-}

-- | 'j2SegmentZipCode' Lens
j2SegmentZipCodeL :: Lens_' J2Segment (Text)
j2SegmentZipCodeL f J2Segment{..} = (\j2SegmentZipCode -> J2Segment { j2SegmentZipCode, ..} ) <$> f j2SegmentZipCode
{-# INLINE j2SegmentZipCodeL #-}

-- | 'j2SegmentAddressIndicator' Lens
j2SegmentAddressIndicatorL :: Lens_' J2Segment (Maybe E'AddressIndicator)
j2SegmentAddressIndicatorL f J2Segment{..} = (\j2SegmentAddressIndicator -> J2Segment { j2SegmentAddressIndicator, ..} ) <$> f j2SegmentAddressIndicator
{-# INLINE j2SegmentAddressIndicatorL #-}

-- | 'j2SegmentResidenceCode' Lens
j2SegmentResidenceCodeL :: Lens_' J2Segment (Maybe E'ResidenceCode)
j2SegmentResidenceCodeL f J2Segment{..} = (\j2SegmentResidenceCode -> J2Segment { j2SegmentResidenceCode, ..} ) <$> f j2SegmentResidenceCode
{-# INLINE j2SegmentResidenceCodeL #-}



-- * K1Segment

-- | 'k1SegmentSegmentIdentifier' Lens
k1SegmentSegmentIdentifierL :: Lens_' K1Segment (E'SegmentIdentifier3)
k1SegmentSegmentIdentifierL f K1Segment{..} = (\k1SegmentSegmentIdentifier -> K1Segment { k1SegmentSegmentIdentifier, ..} ) <$> f k1SegmentSegmentIdentifier
{-# INLINE k1SegmentSegmentIdentifierL #-}

-- | 'k1SegmentOriginalCreditorName' Lens
k1SegmentOriginalCreditorNameL :: Lens_' K1Segment (Text)
k1SegmentOriginalCreditorNameL f K1Segment{..} = (\k1SegmentOriginalCreditorName -> K1Segment { k1SegmentOriginalCreditorName, ..} ) <$> f k1SegmentOriginalCreditorName
{-# INLINE k1SegmentOriginalCreditorNameL #-}

-- | 'k1SegmentCreditorClassification' Lens
k1SegmentCreditorClassificationL :: Lens_' K1Segment (E'CreditorClassification)
k1SegmentCreditorClassificationL f K1Segment{..} = (\k1SegmentCreditorClassification -> K1Segment { k1SegmentCreditorClassification, ..} ) <$> f k1SegmentCreditorClassification
{-# INLINE k1SegmentCreditorClassificationL #-}



-- * K2Segment

-- | 'k2SegmentSegmentIdentifier' Lens
k2SegmentSegmentIdentifierL :: Lens_' K2Segment (E'SegmentIdentifier4)
k2SegmentSegmentIdentifierL f K2Segment{..} = (\k2SegmentSegmentIdentifier -> K2Segment { k2SegmentSegmentIdentifier, ..} ) <$> f k2SegmentSegmentIdentifier
{-# INLINE k2SegmentSegmentIdentifierL #-}

-- | 'k2SegmentPurchasedIndicator' Lens
k2SegmentPurchasedIndicatorL :: Lens_' K2Segment (E'PurchasedIndicator)
k2SegmentPurchasedIndicatorL f K2Segment{..} = (\k2SegmentPurchasedIndicator -> K2Segment { k2SegmentPurchasedIndicator, ..} ) <$> f k2SegmentPurchasedIndicator
{-# INLINE k2SegmentPurchasedIndicatorL #-}

-- | 'k2SegmentPurchasedName' Lens
k2SegmentPurchasedNameL :: Lens_' K2Segment (Text)
k2SegmentPurchasedNameL f K2Segment{..} = (\k2SegmentPurchasedName -> K2Segment { k2SegmentPurchasedName, ..} ) <$> f k2SegmentPurchasedName
{-# INLINE k2SegmentPurchasedNameL #-}



-- * K3Segment

-- | 'k3SegmentSegmentIdentifier' Lens
k3SegmentSegmentIdentifierL :: Lens_' K3Segment (E'SegmentIdentifier5)
k3SegmentSegmentIdentifierL f K3Segment{..} = (\k3SegmentSegmentIdentifier -> K3Segment { k3SegmentSegmentIdentifier, ..} ) <$> f k3SegmentSegmentIdentifier
{-# INLINE k3SegmentSegmentIdentifierL #-}

-- | 'k3SegmentAgencyIdentifier' Lens
k3SegmentAgencyIdentifierL :: Lens_' K3Segment (Maybe E'AgencyIdentifier)
k3SegmentAgencyIdentifierL f K3Segment{..} = (\k3SegmentAgencyIdentifier -> K3Segment { k3SegmentAgencyIdentifier, ..} ) <$> f k3SegmentAgencyIdentifier
{-# INLINE k3SegmentAgencyIdentifierL #-}

-- | 'k3SegmentAccountNumber' Lens
k3SegmentAccountNumberL :: Lens_' K3Segment (Maybe Text)
k3SegmentAccountNumberL f K3Segment{..} = (\k3SegmentAccountNumber -> K3Segment { k3SegmentAccountNumber, ..} ) <$> f k3SegmentAccountNumber
{-# INLINE k3SegmentAccountNumberL #-}

-- | 'k3SegmentMortgageIdentificationNumber' Lens
k3SegmentMortgageIdentificationNumberL :: Lens_' K3Segment (Maybe Text)
k3SegmentMortgageIdentificationNumberL f K3Segment{..} = (\k3SegmentMortgageIdentificationNumber -> K3Segment { k3SegmentMortgageIdentificationNumber, ..} ) <$> f k3SegmentMortgageIdentificationNumber
{-# INLINE k3SegmentMortgageIdentificationNumberL #-}



-- * K4Segment

-- | 'k4SegmentSegmentIdentifier' Lens
k4SegmentSegmentIdentifierL :: Lens_' K4Segment (E'SegmentIdentifier6)
k4SegmentSegmentIdentifierL f K4Segment{..} = (\k4SegmentSegmentIdentifier -> K4Segment { k4SegmentSegmentIdentifier, ..} ) <$> f k4SegmentSegmentIdentifier
{-# INLINE k4SegmentSegmentIdentifierL #-}

-- | 'k4SegmentSpecializedPaymentIndicator' Lens
k4SegmentSpecializedPaymentIndicatorL :: Lens_' K4Segment (E'SpecializedPaymentIndicator)
k4SegmentSpecializedPaymentIndicatorL f K4Segment{..} = (\k4SegmentSpecializedPaymentIndicator -> K4Segment { k4SegmentSpecializedPaymentIndicator, ..} ) <$> f k4SegmentSpecializedPaymentIndicator
{-# INLINE k4SegmentSpecializedPaymentIndicatorL #-}

-- | 'k4SegmentDeferredPaymentStartDate' Lens
k4SegmentDeferredPaymentStartDateL :: Lens_' K4Segment (Maybe DateTime)
k4SegmentDeferredPaymentStartDateL f K4Segment{..} = (\k4SegmentDeferredPaymentStartDate -> K4Segment { k4SegmentDeferredPaymentStartDate, ..} ) <$> f k4SegmentDeferredPaymentStartDate
{-# INLINE k4SegmentDeferredPaymentStartDateL #-}

-- | 'k4SegmentBalloonPaymentDueDate' Lens
k4SegmentBalloonPaymentDueDateL :: Lens_' K4Segment (Maybe DateTime)
k4SegmentBalloonPaymentDueDateL f K4Segment{..} = (\k4SegmentBalloonPaymentDueDate -> K4Segment { k4SegmentBalloonPaymentDueDate, ..} ) <$> f k4SegmentBalloonPaymentDueDate
{-# INLINE k4SegmentBalloonPaymentDueDateL #-}

-- | 'k4SegmentBalloonPaymentAmount' Lens
k4SegmentBalloonPaymentAmountL :: Lens_' K4Segment (Maybe Int)
k4SegmentBalloonPaymentAmountL f K4Segment{..} = (\k4SegmentBalloonPaymentAmount -> K4Segment { k4SegmentBalloonPaymentAmount, ..} ) <$> f k4SegmentBalloonPaymentAmount
{-# INLINE k4SegmentBalloonPaymentAmountL #-}



-- * L1Segment

-- | 'l1SegmentSegmentIdentifier' Lens
l1SegmentSegmentIdentifierL :: Lens_' L1Segment (E'SegmentIdentifier7)
l1SegmentSegmentIdentifierL f L1Segment{..} = (\l1SegmentSegmentIdentifier -> L1Segment { l1SegmentSegmentIdentifier, ..} ) <$> f l1SegmentSegmentIdentifier
{-# INLINE l1SegmentSegmentIdentifierL #-}

-- | 'l1SegmentChangeIndicator' Lens
l1SegmentChangeIndicatorL :: Lens_' L1Segment (Int)
l1SegmentChangeIndicatorL f L1Segment{..} = (\l1SegmentChangeIndicator -> L1Segment { l1SegmentChangeIndicator, ..} ) <$> f l1SegmentChangeIndicator
{-# INLINE l1SegmentChangeIndicatorL #-}

-- | 'l1SegmentNewConsumerAccountNumber' Lens
l1SegmentNewConsumerAccountNumberL :: Lens_' L1Segment (Maybe Text)
l1SegmentNewConsumerAccountNumberL f L1Segment{..} = (\l1SegmentNewConsumerAccountNumber -> L1Segment { l1SegmentNewConsumerAccountNumber, ..} ) <$> f l1SegmentNewConsumerAccountNumber
{-# INLINE l1SegmentNewConsumerAccountNumberL #-}

-- | 'l1SegmentBalloonPaymentDueDate' Lens
l1SegmentBalloonPaymentDueDateL :: Lens_' L1Segment (Maybe Text)
l1SegmentBalloonPaymentDueDateL f L1Segment{..} = (\l1SegmentBalloonPaymentDueDate -> L1Segment { l1SegmentBalloonPaymentDueDate, ..} ) <$> f l1SegmentBalloonPaymentDueDate
{-# INLINE l1SegmentBalloonPaymentDueDateL #-}



-- * N1Segment

-- | 'n1SegmentSegmentIdentifier' Lens
n1SegmentSegmentIdentifierL :: Lens_' N1Segment (E'SegmentIdentifier8)
n1SegmentSegmentIdentifierL f N1Segment{..} = (\n1SegmentSegmentIdentifier -> N1Segment { n1SegmentSegmentIdentifier, ..} ) <$> f n1SegmentSegmentIdentifier
{-# INLINE n1SegmentSegmentIdentifierL #-}

-- | 'n1SegmentEmployerName' Lens
n1SegmentEmployerNameL :: Lens_' N1Segment (Text)
n1SegmentEmployerNameL f N1Segment{..} = (\n1SegmentEmployerName -> N1Segment { n1SegmentEmployerName, ..} ) <$> f n1SegmentEmployerName
{-# INLINE n1SegmentEmployerNameL #-}

-- | 'n1SegmentFirstLineEmployerAddress' Lens
n1SegmentFirstLineEmployerAddressL :: Lens_' N1Segment (Maybe Text)
n1SegmentFirstLineEmployerAddressL f N1Segment{..} = (\n1SegmentFirstLineEmployerAddress -> N1Segment { n1SegmentFirstLineEmployerAddress, ..} ) <$> f n1SegmentFirstLineEmployerAddress
{-# INLINE n1SegmentFirstLineEmployerAddressL #-}

-- | 'n1SegmentSecondLineEmployerAddress' Lens
n1SegmentSecondLineEmployerAddressL :: Lens_' N1Segment (Maybe Text)
n1SegmentSecondLineEmployerAddressL f N1Segment{..} = (\n1SegmentSecondLineEmployerAddress -> N1Segment { n1SegmentSecondLineEmployerAddress, ..} ) <$> f n1SegmentSecondLineEmployerAddress
{-# INLINE n1SegmentSecondLineEmployerAddressL #-}

-- | 'n1SegmentEmployerCity' Lens
n1SegmentEmployerCityL :: Lens_' N1Segment (Maybe Text)
n1SegmentEmployerCityL f N1Segment{..} = (\n1SegmentEmployerCity -> N1Segment { n1SegmentEmployerCity, ..} ) <$> f n1SegmentEmployerCity
{-# INLINE n1SegmentEmployerCityL #-}

-- | 'n1SegmentEmployerState' Lens
n1SegmentEmployerStateL :: Lens_' N1Segment (Maybe Text)
n1SegmentEmployerStateL f N1Segment{..} = (\n1SegmentEmployerState -> N1Segment { n1SegmentEmployerState, ..} ) <$> f n1SegmentEmployerState
{-# INLINE n1SegmentEmployerStateL #-}

-- | 'n1SegmentZipCode' Lens
n1SegmentZipCodeL :: Lens_' N1Segment (Maybe Text)
n1SegmentZipCodeL f N1Segment{..} = (\n1SegmentZipCode -> N1Segment { n1SegmentZipCode, ..} ) <$> f n1SegmentZipCode
{-# INLINE n1SegmentZipCodeL #-}

-- | 'n1SegmentOccupation' Lens
n1SegmentOccupationL :: Lens_' N1Segment (Maybe Text)
n1SegmentOccupationL f N1Segment{..} = (\n1SegmentOccupation -> N1Segment { n1SegmentOccupation, ..} ) <$> f n1SegmentOccupation
{-# INLINE n1SegmentOccupationL #-}



-- * TrailerRecord

-- | 'trailerRecordBlockDescriptorWord' Lens
trailerRecordBlockDescriptorWordL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordBlockDescriptorWordL f TrailerRecord{..} = (\trailerRecordBlockDescriptorWord -> TrailerRecord { trailerRecordBlockDescriptorWord, ..} ) <$> f trailerRecordBlockDescriptorWord
{-# INLINE trailerRecordBlockDescriptorWordL #-}

-- | 'trailerRecordRecordDescriptorWord' Lens
trailerRecordRecordDescriptorWordL :: Lens_' TrailerRecord (Int)
trailerRecordRecordDescriptorWordL f TrailerRecord{..} = (\trailerRecordRecordDescriptorWord -> TrailerRecord { trailerRecordRecordDescriptorWord, ..} ) <$> f trailerRecordRecordDescriptorWord
{-# INLINE trailerRecordRecordDescriptorWordL #-}

-- | 'trailerRecordRecordIdentifier' Lens
trailerRecordRecordIdentifierL :: Lens_' TrailerRecord (E'RecordIdentifier2)
trailerRecordRecordIdentifierL f TrailerRecord{..} = (\trailerRecordRecordIdentifier -> TrailerRecord { trailerRecordRecordIdentifier, ..} ) <$> f trailerRecordRecordIdentifier
{-# INLINE trailerRecordRecordIdentifierL #-}

-- | 'trailerRecordTotalBaseRecords' Lens
trailerRecordTotalBaseRecordsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalBaseRecordsL f TrailerRecord{..} = (\trailerRecordTotalBaseRecords -> TrailerRecord { trailerRecordTotalBaseRecords, ..} ) <$> f trailerRecordTotalBaseRecords
{-# INLINE trailerRecordTotalBaseRecordsL #-}

-- | 'trailerRecordTotalStatusCodeDf' Lens
trailerRecordTotalStatusCodeDfL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCodeDfL f TrailerRecord{..} = (\trailerRecordTotalStatusCodeDf -> TrailerRecord { trailerRecordTotalStatusCodeDf, ..} ) <$> f trailerRecordTotalStatusCodeDf
{-# INLINE trailerRecordTotalStatusCodeDfL #-}

-- | 'trailerRecordTotalConsumerSegmentsJ1' Lens
trailerRecordTotalConsumerSegmentsJ1L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalConsumerSegmentsJ1L f TrailerRecord{..} = (\trailerRecordTotalConsumerSegmentsJ1 -> TrailerRecord { trailerRecordTotalConsumerSegmentsJ1, ..} ) <$> f trailerRecordTotalConsumerSegmentsJ1
{-# INLINE trailerRecordTotalConsumerSegmentsJ1L #-}

-- | 'trailerRecordTotalConsumerSegmentsJ2' Lens
trailerRecordTotalConsumerSegmentsJ2L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalConsumerSegmentsJ2L f TrailerRecord{..} = (\trailerRecordTotalConsumerSegmentsJ2 -> TrailerRecord { trailerRecordTotalConsumerSegmentsJ2, ..} ) <$> f trailerRecordTotalConsumerSegmentsJ2
{-# INLINE trailerRecordTotalConsumerSegmentsJ2L #-}

-- | 'trailerRecordBlockCount' Lens
trailerRecordBlockCountL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordBlockCountL f TrailerRecord{..} = (\trailerRecordBlockCount -> TrailerRecord { trailerRecordBlockCount, ..} ) <$> f trailerRecordBlockCount
{-# INLINE trailerRecordBlockCountL #-}

-- | 'trailerRecordTotalStatusCodeDa' Lens
trailerRecordTotalStatusCodeDaL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCodeDaL f TrailerRecord{..} = (\trailerRecordTotalStatusCodeDa -> TrailerRecord { trailerRecordTotalStatusCodeDa, ..} ) <$> f trailerRecordTotalStatusCodeDa
{-# INLINE trailerRecordTotalStatusCodeDaL #-}

-- | 'trailerRecordTotalStatusCode05' Lens
trailerRecordTotalStatusCode05L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode05L f TrailerRecord{..} = (\trailerRecordTotalStatusCode05 -> TrailerRecord { trailerRecordTotalStatusCode05, ..} ) <$> f trailerRecordTotalStatusCode05
{-# INLINE trailerRecordTotalStatusCode05L #-}

-- | 'trailerRecordTotalStatusCode11' Lens
trailerRecordTotalStatusCode11L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode11L f TrailerRecord{..} = (\trailerRecordTotalStatusCode11 -> TrailerRecord { trailerRecordTotalStatusCode11, ..} ) <$> f trailerRecordTotalStatusCode11
{-# INLINE trailerRecordTotalStatusCode11L #-}

-- | 'trailerRecordTotalStatusCode13' Lens
trailerRecordTotalStatusCode13L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode13L f TrailerRecord{..} = (\trailerRecordTotalStatusCode13 -> TrailerRecord { trailerRecordTotalStatusCode13, ..} ) <$> f trailerRecordTotalStatusCode13
{-# INLINE trailerRecordTotalStatusCode13L #-}

-- | 'trailerRecordTotalStatusCode61' Lens
trailerRecordTotalStatusCode61L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode61L f TrailerRecord{..} = (\trailerRecordTotalStatusCode61 -> TrailerRecord { trailerRecordTotalStatusCode61, ..} ) <$> f trailerRecordTotalStatusCode61
{-# INLINE trailerRecordTotalStatusCode61L #-}

-- | 'trailerRecordTotalStatusCode62' Lens
trailerRecordTotalStatusCode62L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode62L f TrailerRecord{..} = (\trailerRecordTotalStatusCode62 -> TrailerRecord { trailerRecordTotalStatusCode62, ..} ) <$> f trailerRecordTotalStatusCode62
{-# INLINE trailerRecordTotalStatusCode62L #-}

-- | 'trailerRecordTotalStatusCode63' Lens
trailerRecordTotalStatusCode63L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode63L f TrailerRecord{..} = (\trailerRecordTotalStatusCode63 -> TrailerRecord { trailerRecordTotalStatusCode63, ..} ) <$> f trailerRecordTotalStatusCode63
{-# INLINE trailerRecordTotalStatusCode63L #-}

-- | 'trailerRecordTotalStatusCode64' Lens
trailerRecordTotalStatusCode64L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode64L f TrailerRecord{..} = (\trailerRecordTotalStatusCode64 -> TrailerRecord { trailerRecordTotalStatusCode64, ..} ) <$> f trailerRecordTotalStatusCode64
{-# INLINE trailerRecordTotalStatusCode64L #-}

-- | 'trailerRecordTotalStatusCode65' Lens
trailerRecordTotalStatusCode65L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode65L f TrailerRecord{..} = (\trailerRecordTotalStatusCode65 -> TrailerRecord { trailerRecordTotalStatusCode65, ..} ) <$> f trailerRecordTotalStatusCode65
{-# INLINE trailerRecordTotalStatusCode65L #-}

-- | 'trailerRecordTotalStatusCode71' Lens
trailerRecordTotalStatusCode71L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode71L f TrailerRecord{..} = (\trailerRecordTotalStatusCode71 -> TrailerRecord { trailerRecordTotalStatusCode71, ..} ) <$> f trailerRecordTotalStatusCode71
{-# INLINE trailerRecordTotalStatusCode71L #-}

-- | 'trailerRecordTotalStatusCode78' Lens
trailerRecordTotalStatusCode78L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode78L f TrailerRecord{..} = (\trailerRecordTotalStatusCode78 -> TrailerRecord { trailerRecordTotalStatusCode78, ..} ) <$> f trailerRecordTotalStatusCode78
{-# INLINE trailerRecordTotalStatusCode78L #-}

-- | 'trailerRecordTotalStatusCode80' Lens
trailerRecordTotalStatusCode80L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode80L f TrailerRecord{..} = (\trailerRecordTotalStatusCode80 -> TrailerRecord { trailerRecordTotalStatusCode80, ..} ) <$> f trailerRecordTotalStatusCode80
{-# INLINE trailerRecordTotalStatusCode80L #-}

-- | 'trailerRecordTotalStatusCode82' Lens
trailerRecordTotalStatusCode82L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode82L f TrailerRecord{..} = (\trailerRecordTotalStatusCode82 -> TrailerRecord { trailerRecordTotalStatusCode82, ..} ) <$> f trailerRecordTotalStatusCode82
{-# INLINE trailerRecordTotalStatusCode82L #-}

-- | 'trailerRecordTotalStatusCode83' Lens
trailerRecordTotalStatusCode83L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode83L f TrailerRecord{..} = (\trailerRecordTotalStatusCode83 -> TrailerRecord { trailerRecordTotalStatusCode83, ..} ) <$> f trailerRecordTotalStatusCode83
{-# INLINE trailerRecordTotalStatusCode83L #-}

-- | 'trailerRecordTotalStatusCode84' Lens
trailerRecordTotalStatusCode84L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode84L f TrailerRecord{..} = (\trailerRecordTotalStatusCode84 -> TrailerRecord { trailerRecordTotalStatusCode84, ..} ) <$> f trailerRecordTotalStatusCode84
{-# INLINE trailerRecordTotalStatusCode84L #-}

-- | 'trailerRecordTotalStatusCode88' Lens
trailerRecordTotalStatusCode88L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode88L f TrailerRecord{..} = (\trailerRecordTotalStatusCode88 -> TrailerRecord { trailerRecordTotalStatusCode88, ..} ) <$> f trailerRecordTotalStatusCode88
{-# INLINE trailerRecordTotalStatusCode88L #-}

-- | 'trailerRecordTotalStatusCode89' Lens
trailerRecordTotalStatusCode89L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode89L f TrailerRecord{..} = (\trailerRecordTotalStatusCode89 -> TrailerRecord { trailerRecordTotalStatusCode89, ..} ) <$> f trailerRecordTotalStatusCode89
{-# INLINE trailerRecordTotalStatusCode89L #-}

-- | 'trailerRecordTotalStatusCode93' Lens
trailerRecordTotalStatusCode93L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode93L f TrailerRecord{..} = (\trailerRecordTotalStatusCode93 -> TrailerRecord { trailerRecordTotalStatusCode93, ..} ) <$> f trailerRecordTotalStatusCode93
{-# INLINE trailerRecordTotalStatusCode93L #-}

-- | 'trailerRecordTotalStatusCode94' Lens
trailerRecordTotalStatusCode94L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode94L f TrailerRecord{..} = (\trailerRecordTotalStatusCode94 -> TrailerRecord { trailerRecordTotalStatusCode94, ..} ) <$> f trailerRecordTotalStatusCode94
{-# INLINE trailerRecordTotalStatusCode94L #-}

-- | 'trailerRecordTotalStatusCode95' Lens
trailerRecordTotalStatusCode95L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode95L f TrailerRecord{..} = (\trailerRecordTotalStatusCode95 -> TrailerRecord { trailerRecordTotalStatusCode95, ..} ) <$> f trailerRecordTotalStatusCode95
{-# INLINE trailerRecordTotalStatusCode95L #-}

-- | 'trailerRecordTotalStatusCode96' Lens
trailerRecordTotalStatusCode96L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode96L f TrailerRecord{..} = (\trailerRecordTotalStatusCode96 -> TrailerRecord { trailerRecordTotalStatusCode96, ..} ) <$> f trailerRecordTotalStatusCode96
{-# INLINE trailerRecordTotalStatusCode96L #-}

-- | 'trailerRecordTotalStatusCode97' Lens
trailerRecordTotalStatusCode97L :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalStatusCode97L f TrailerRecord{..} = (\trailerRecordTotalStatusCode97 -> TrailerRecord { trailerRecordTotalStatusCode97, ..} ) <$> f trailerRecordTotalStatusCode97
{-# INLINE trailerRecordTotalStatusCode97L #-}

-- | 'trailerRecordTotalEcoaCodeZ' Lens
trailerRecordTotalEcoaCodeZL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalEcoaCodeZL f TrailerRecord{..} = (\trailerRecordTotalEcoaCodeZ -> TrailerRecord { trailerRecordTotalEcoaCodeZ, ..} ) <$> f trailerRecordTotalEcoaCodeZ
{-# INLINE trailerRecordTotalEcoaCodeZL #-}

-- | 'trailerRecordTotalEmploymentSegments' Lens
trailerRecordTotalEmploymentSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalEmploymentSegmentsL f TrailerRecord{..} = (\trailerRecordTotalEmploymentSegments -> TrailerRecord { trailerRecordTotalEmploymentSegments, ..} ) <$> f trailerRecordTotalEmploymentSegments
{-# INLINE trailerRecordTotalEmploymentSegmentsL #-}

-- | 'trailerRecordTotalOriginalCreditorSegments' Lens
trailerRecordTotalOriginalCreditorSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalOriginalCreditorSegmentsL f TrailerRecord{..} = (\trailerRecordTotalOriginalCreditorSegments -> TrailerRecord { trailerRecordTotalOriginalCreditorSegments, ..} ) <$> f trailerRecordTotalOriginalCreditorSegments
{-# INLINE trailerRecordTotalOriginalCreditorSegmentsL #-}

-- | 'trailerRecordTotalPurchasedToSegments' Lens
trailerRecordTotalPurchasedToSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalPurchasedToSegmentsL f TrailerRecord{..} = (\trailerRecordTotalPurchasedToSegments -> TrailerRecord { trailerRecordTotalPurchasedToSegments, ..} ) <$> f trailerRecordTotalPurchasedToSegments
{-# INLINE trailerRecordTotalPurchasedToSegmentsL #-}

-- | 'trailerRecordTotalMortgageInformationSegments' Lens
trailerRecordTotalMortgageInformationSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalMortgageInformationSegmentsL f TrailerRecord{..} = (\trailerRecordTotalMortgageInformationSegments -> TrailerRecord { trailerRecordTotalMortgageInformationSegments, ..} ) <$> f trailerRecordTotalMortgageInformationSegments
{-# INLINE trailerRecordTotalMortgageInformationSegmentsL #-}

-- | 'trailerRecordTotalPaymentInformationSegments' Lens
trailerRecordTotalPaymentInformationSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalPaymentInformationSegmentsL f TrailerRecord{..} = (\trailerRecordTotalPaymentInformationSegments -> TrailerRecord { trailerRecordTotalPaymentInformationSegments, ..} ) <$> f trailerRecordTotalPaymentInformationSegments
{-# INLINE trailerRecordTotalPaymentInformationSegmentsL #-}

-- | 'trailerRecordTotalChangeSegments' Lens
trailerRecordTotalChangeSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalChangeSegmentsL f TrailerRecord{..} = (\trailerRecordTotalChangeSegments -> TrailerRecord { trailerRecordTotalChangeSegments, ..} ) <$> f trailerRecordTotalChangeSegments
{-# INLINE trailerRecordTotalChangeSegmentsL #-}

-- | 'trailerRecordTotalSocialNumbersAllSegments' Lens
trailerRecordTotalSocialNumbersAllSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalSocialNumbersAllSegmentsL f TrailerRecord{..} = (\trailerRecordTotalSocialNumbersAllSegments -> TrailerRecord { trailerRecordTotalSocialNumbersAllSegments, ..} ) <$> f trailerRecordTotalSocialNumbersAllSegments
{-# INLINE trailerRecordTotalSocialNumbersAllSegmentsL #-}

-- | 'trailerRecordTotalSocialNumbersBaseSegments' Lens
trailerRecordTotalSocialNumbersBaseSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalSocialNumbersBaseSegmentsL f TrailerRecord{..} = (\trailerRecordTotalSocialNumbersBaseSegments -> TrailerRecord { trailerRecordTotalSocialNumbersBaseSegments, ..} ) <$> f trailerRecordTotalSocialNumbersBaseSegments
{-# INLINE trailerRecordTotalSocialNumbersBaseSegmentsL #-}

-- | 'trailerRecordTotalSocialNumbersJ1Segments' Lens
trailerRecordTotalSocialNumbersJ1SegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalSocialNumbersJ1SegmentsL f TrailerRecord{..} = (\trailerRecordTotalSocialNumbersJ1Segments -> TrailerRecord { trailerRecordTotalSocialNumbersJ1Segments, ..} ) <$> f trailerRecordTotalSocialNumbersJ1Segments
{-# INLINE trailerRecordTotalSocialNumbersJ1SegmentsL #-}

-- | 'trailerRecordTotalSocialNumbersJ2Segments' Lens
trailerRecordTotalSocialNumbersJ2SegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalSocialNumbersJ2SegmentsL f TrailerRecord{..} = (\trailerRecordTotalSocialNumbersJ2Segments -> TrailerRecord { trailerRecordTotalSocialNumbersJ2Segments, ..} ) <$> f trailerRecordTotalSocialNumbersJ2Segments
{-# INLINE trailerRecordTotalSocialNumbersJ2SegmentsL #-}

-- | 'trailerRecordTotalDatesBirthAllSegments' Lens
trailerRecordTotalDatesBirthAllSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalDatesBirthAllSegmentsL f TrailerRecord{..} = (\trailerRecordTotalDatesBirthAllSegments -> TrailerRecord { trailerRecordTotalDatesBirthAllSegments, ..} ) <$> f trailerRecordTotalDatesBirthAllSegments
{-# INLINE trailerRecordTotalDatesBirthAllSegmentsL #-}

-- | 'trailerRecordTotalDatesBirthBaseSegments' Lens
trailerRecordTotalDatesBirthBaseSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalDatesBirthBaseSegmentsL f TrailerRecord{..} = (\trailerRecordTotalDatesBirthBaseSegments -> TrailerRecord { trailerRecordTotalDatesBirthBaseSegments, ..} ) <$> f trailerRecordTotalDatesBirthBaseSegments
{-# INLINE trailerRecordTotalDatesBirthBaseSegmentsL #-}

-- | 'trailerRecordTotalDatesBirthJ1Segments' Lens
trailerRecordTotalDatesBirthJ1SegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalDatesBirthJ1SegmentsL f TrailerRecord{..} = (\trailerRecordTotalDatesBirthJ1Segments -> TrailerRecord { trailerRecordTotalDatesBirthJ1Segments, ..} ) <$> f trailerRecordTotalDatesBirthJ1Segments
{-# INLINE trailerRecordTotalDatesBirthJ1SegmentsL #-}

-- | 'trailerRecordTotalDatesBirthJ2Segments' Lens
trailerRecordTotalDatesBirthJ2SegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalDatesBirthJ2SegmentsL f TrailerRecord{..} = (\trailerRecordTotalDatesBirthJ2Segments -> TrailerRecord { trailerRecordTotalDatesBirthJ2Segments, ..} ) <$> f trailerRecordTotalDatesBirthJ2Segments
{-# INLINE trailerRecordTotalDatesBirthJ2SegmentsL #-}

-- | 'trailerRecordTotalTelephoneNumbersAllSegments' Lens
trailerRecordTotalTelephoneNumbersAllSegmentsL :: Lens_' TrailerRecord (Maybe Int)
trailerRecordTotalTelephoneNumbersAllSegmentsL f TrailerRecord{..} = (\trailerRecordTotalTelephoneNumbersAllSegments -> TrailerRecord { trailerRecordTotalTelephoneNumbersAllSegments, ..} ) <$> f trailerRecordTotalTelephoneNumbersAllSegments
{-# INLINE trailerRecordTotalTelephoneNumbersAllSegmentsL #-}


